#if !canImport(ObjectiveC)
import XCTest

extension JSONUtilTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONUtilTests = [
        ("testExample", testExample),
        ("testMakePatch", testMakePatch),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONUtilTests.__allTests__JSONUtilTests),
    ]
}
#endif
